### ISSUE TITLE
Carte de la fraicheur en cas de canicule

### ISSUE THREAD

**Issue by laem** [laem/cartes#381]
https://x.com/PatrickRerat/status/1803003044453368024/photo/1

Dans une v1 ça consiste juste à ajouter une liste de ce style. 

À noter, les rivières sont des relations non convexes et le dessin foire du coup, c'est moche. 

Il faudrait dessiner en bleu l'eau, en vert les parcs, en marron les zones ombragées ? 

```
- name: fraicheur
  category: Lieux de fraicheur
  title: Où aller en cas de canicule
  dictionary:
    - végétalien
  query:
    - '["amenity"="fountain"]'
    # Verdure
    - '[leisure~"park|nature_reserve"]'
    - '[boundary=national_park]'
    - '[waterway=river]'
  icon: veg

```
